### ISSUE TITLE
[1.20.1] Mod does not load

### ISSUE THREAD

**Issue by Deepacat** [MCTian-mi/Gregfluxology#5]
Was already reported... but on the wrong repo
Is the mod even made for 1.20.1? I went looking to see if I could take a look myself, but there is no branch or history for a 1.20.1 release

Here is the log anyway 
`[15Dec2024 02:14:20.547] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: gregfluxology, class gregfluxology.Gregfluxology
java.lang.NoSuchMethodException: gregfluxology.Gregfluxology.<init>()
	at java.lang.Class.getConstructor0(Class.java:3761) ~[?:?]
	at java.lang.Class.getDeclaredConstructor(Class.java:2930) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.6.jar%23412!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.6.jar%23411!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]`

**Comment by MCTian-mi** [comment]
ah I kinda forgot to upload the code for 1.20.1
might get this fixed later this week

**Comment by MCTian-mi** [comment]
what forge version are you on
this works on latest lexforge (47.3.22)
